### ISSUE TITLE
TO-DO List for Version 0.0.3

### ISSUE THREAD

**Issue by RandomAltThing** [DragonetMC/Dragonet#58]
**TODO List for Dragonet version 0.0.3**

- [ ] Fix #48 
- [ ] Fix #46 (if not fixed already)
- [ ] Block placing lag
- [ ] Item crafting lag

**0.12.1 packets and protocal update in a future milestone**

**Comment by RandomAltThing** [comment]
@DefinitlyEvil I think 0.0.3 can mosy be a bugfix update... I will eventually contribute actual code but I got my own project to work on.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Mostly*  not mosy (Cba to go into desktop more I'm on my phone)

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Thanks for taking time helping me. I am too busy to do this right now, I can only do the core part(such as networking) for now and I can't spend time fixing errors.

**Comment by jython234** [comment]
One thing this repository needs is a decent structure. I saw a POM, but it's labeled as "backup". Why? We should use maven.

**Comment by TekkitCommando** [comment]
Maven helps with dependancy management

**Comment by TekkitCommando** [comment]
I like gradle but you know, I dont have too much experience with maven so thats probly why

**Comment by RandomAltThing** [comment]
@TekkitCommando I don't know the difference, I only.know of gradle and eclipse xD

**Comment by TekkitCommando** [comment]
xD

**Comment by DefinitlyEvil** [comment]
@jython234 I can't access JRakLib repo.

**Comment by mastercoms** [comment]
Could someone describe item crafting lag? Is it laggy on PE and PC, or just PE?

**Comment by DefinitlyEvil** [comment]
@mastercoms Since you fixed the item duplication bug, I think this bug is only on PE due to bad packet handling.

**Comment by RandomAltThing** [comment]
@Jython234 Did you fix disconnecting in JRakLib?

**Comment by mastercoms** [comment]
I'm going to be rewriting the config code for Glowstone++ soon, in preparation for the new world manager, so if that's what you mean by better file structure, you should wait until that update.

**Comment by RandomAltThing** [comment]
@mastercoms I was talking about what @jython234 said about it being hard to build. He also said that the glowstone code shouldn't be in the dragonet directory or something (can't remember). But @DefinitlyEvil Prefers it the way that it currently is. He can remove it from the TODO is he wants.

**Comment by RandomAltThing** [comment]
@jython234 Oh nvm lol its already ticked so it was fixed. Hard to see on a mobile device.

**Comment by RandomAltThing** [comment]
Any work on item lag? @mastercoms

**Comment by mastercoms** [comment]
Item lag?

**Comment by RandomAltThing** [comment]
It was in an issue its still unchecked in the TODO list

**Comment by RandomAltThing** [comment]
I will check it off then

**Comment by mastercoms** [comment]
But it isn't done for Dragonet.

**Comment by RandomAltThing** [comment]
I have added one more todo which is for more enchantments for pe work

**Comment by RandomAltThing** [comment]
DefinitlyEvil said I could work on them but its hard due to half the code being in glow stone already

**Comment by mastercoms** [comment]
It should be PE Enhancements. We're not wizards here.

**Comment by RandomAltThing** [comment]
I might make some PR's to glowstone.

**Comment by mastercoms** [comment]
What kind of PRs?

**Comment by RandomAltThing** [comment]
@mastercoms Idk is there a TODO list?

**Comment by mastercoms** [comment]
Could we talk on gitter?

**Comment by RandomAltThing** [comment]
And would I commit to Glowstone or Gloekit

**Comment by mastercoms** [comment]
Here: https://gitter.im/GlowstonePlusPlus/GlowstonePlusPlus
